### ISSUE TITLE
Bower Packages Out of Date

### ISSUE THREAD

**Issue by bdbonnet** [PredixDev/generator-px-comp#15]
After running `yo px-comp`, I found that older versions of Polymer, px-theme, px-stater-design-kit, and px-demo were installed.

The bower file just needs to be updated to reflect the newer releases.

**Comment by bdbonnet** [comment]
So, I installed the generator via npm and ran it through Yeoman. I took a look at the npm registry, and it looks like the version on there is actually the sticky wicket. It's currently set at 0.4.6.

**Comment by mdwragg** [comment]
We were waiting for the release tomorrow but I just published v1.0.0 to NPM:

https://www.npmjs.com/package/generator-px-comp

Update your installed version and everything should be happy 👍 🐐 🍶 🎉

**Comment by mdwragg** [comment]
Please test it out and close the issue if all OK. Thanks!

**Comment by bdbonnet** [comment]
Excellent!

Sorry to jump the gun 😅

**Comment by mdwragg** [comment]
No problem - you caught us in a weird moment as we're releasing All The Things ;)

**Comment by bdbonnet** [comment]
Pulled down the new version, and it all looks great.

Thanks!
