### ISSUE TITLE
yoman script broken due to shifting of template files

### ISSUE THREAD

**Issue by deep1234raj** [PredixDev/generator-px-comp#6]
the yo script cannot find template files in specified location.

Possible solution
in app/index.js
in projectfiles() function

change     
this.copy('.github/PULL_REQUEST_TEMPLATE.md', '.github/PULL_REQUEST_TEMPLATE.md');
to 
this.copy('src/.github/PULL_REQUEST_TEMPLATE.md', '.github/PULL_REQUEST_TEMPLATE.md');

and
this.copy('.github/ISSUE_TEMPLATE.md', '.github/ISSUE_TEMPLATE.md');
to
this.copy('src/.github/ISSUE_TEMPLATE.md', '.github/ISSUE_TEMPLATE.md');

**Comment by runn-vermel** [comment]
Thanks for the PR. fixed this issue and closing issue.
