### ISSUE TITLE
generator should be in the public npm repository

### ISSUE THREAD

**Issue by gstroup** [PredixDev/generator-px-comp#9]
We've now published several other packages to npm.  Would you like me to publish this one?

**Comment by mdwragg** [comment]
It already is!

**Comment by gstroup** [comment]
Oh, great!  Sorry, I guess I was looking at an old version that required npm link.  Thanks.

**Comment by gstroup** [comment]
I guess the README still says to use npm link, that confused me.  Also, if you'd like to publish under the "predix" user on npm, let me know.  Would be nice to have it on this list:  https://www.npmjs.com/~predix

**Comment by mdwragg** [comment]
Done!
